name: testing
on:
  push:
    branches:
      - main      

      
jobs:
  modify-sg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add IP to Security Group
        uses: AI0626-VarshiniAS/aws-security-group@main 
        with:
          account-id: '106'
          aws-region: us-east-1
          security-group-id: sg-09ac666956fd81b39
          port: 22
          protocol: tcp
          action: add
          


