name: testing
on:
  push:
    branches:
      - main
jobs:
  modify-sg:
    runs-on: ubuntu-latest
    steps:
      - name: Run custom IP modifier
        uses: AI0626-VarshiniAS/aws-security-group-action@main 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          security-group-id: sg-09ac666956fd81b39
          port: '22'
          description: 'GitHub runner'
